### ISSUE TITLE
[NEW APP] slskd + soularr

### ISSUE THREAD

**Issue by matthewkdies** [matthewkdies/homeserver#25]
**Description**
slskd connects to the Soulseek network for getting public domain music from other people on the network.
soularr connects the wanted albums from lidarr to the slskd and uses it to download the public domain music.

**Configuration Details**
N/A, both deployable with Docker.
From a quick peed at slskd's docs, it appears there are extra headers necessary when putting it behind a reverse proxy, so I'll have to configure that within Caddy.

I'll likely also want to put both of these behind Authelia.

**Dependencies**
slskd is required for soularr, so I should get that up and running first.

**Additional Information:**
Here's the recommended Docker Compose for slskd from their docs:
```yaml
---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - <path/to/application/data>:/app
    restart: always
```
And the [slskd README](https://github.com/slskd/slskd?tab=readme-ov-file#slskd).

Here's the recommended Docker Compose for soularr from their docs:
```yaml
services:
  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    hostname: soularr
  user: 1000:1000 # this should be set to your UID and GID, which can be determined via `id -u` and `id -g`, respectively
    environment:
      - TZ=Etc/UTC
      - SCRIPT_INTERVAL=300 # Script interval in seconds
    volumes:
      # "You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /Media/slskd_downloads:/downloads
      # Select where you are storing your config file.
      # Leave "/data" since thats where the script expects the config file to be
      - /Containers/soularr:/data
    restart: unless-stopped
```
And the [soularr README](https://github.com/mrusse/soularr?tab=readme-ov-file#about).
